CREATE TABLE "mytable" (
  "/*" text
);

INSERT INTO "mytable" ("/*")
VALUES
('===================================================================================='),
('Project:     FreshCo Foods Inc. Inventory Insights SQL Project'),
('Author:      Xyrus Glenn T. Buenaventura'),
('Description: This project analyzes inentory data to uncover insights related to'),
('inventory value'),
('using SQL. It applies basic'),
('advanced SQL queries.'),
('Tools:       SQL'),
('===================================================================================='),
('*/'),
('-- View the raw data'),
('SELECT *'),
('FROM "FreshCo Foods Inc. Inventory";'),
('-- Total records count'),
('SELECT'),
('COUNT (*) AS Total_records'),
('FROM "FreshCo Foods Inc. Inventory";'),
('-- Total Pallet ID'),
('SELECT "CATEGORY"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('GROUP BY "CATEGORY"'),
('ORDER BY "CATEGORY";'),
('-- Total Pallet ID'),
('SELECT "SUBCATEGORY"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('GROUP BY "SUBCATEGORY"'),
('ORDER BY "SUBCATEGORY";'),
('-- Total Pallet ID'),
('SELECT "WAREHOUSE_NAME"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('GROUP BY "WAREHOUSE_NAME"'),
('ORDER BY "WAREHOUSE_NAME";'),
('-- Total Pallet ID'),
('SELECT "EXPIRY_RISK"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('GROUP BY "EXPIRY_RISK"'),
('ORDER BY "EXPIRY_RISK";'),
('-- Total Pallet ID'),
('SELECT "STATUS"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('GROUP BY "STATUS"'),
('ORDER BY "STATUS";'),
('-- View Nearly Expiry Items by Warehouse'),
('SELECT "WAREHOUSE_NAME"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('WHERE "EXPIRY_RISK" LIKE ''%Critical%'''),
('GROUP BY "WAREHOUSE_NAME"'),
('ORDER BY "WAREHOUSE_NAME";'),
('-- View Already Expired and Critical Items'),
('SELECT'),
('"PALLET_ID"'),
('"SKU"'),
('"DESCRIPTION"'),
('"CATEGORY"'),
('"SUBCATEGORY"'),
('"MFG_DATE"'),
('"EXP_DATE"'),
('"DAYS_TO_EXPIRY"'),
('"AGING_DAYS"'),
('"SHELF_LIFE_DAYS"'),
('"WAREHOUSE_CODE"'),
('"WAREHOUSE_NAME"'),
('"LOCATION"'),
('"QTY_CASES"'),
('"TOTAL_KG"'),
('"TOTAL_VALUE"'),
('"EXPIRY_RISK"'),
('FROM "FreshCo Foods Inc. Inventory"'),
('WHERE "EXPIRY_RISK" LIKE ''%Expired%'''),
('OR "EXPIRY_RISK" LIKE ''%Critical%'';'),
('-- View Already Expired Items'),
('SELECT'),
('"PALLET_ID"'),
('"SKU"'),
('"DESCRIPTION"'),
('"CATEGORY"'),
('"SUBCATEGORY"'),
('"MFG_DATE"'),
('"EXP_DATE"'),
('"DAYS_TO_EXPIRY"'),
('"AGING_DAYS"'),
('"SHELF_LIFE_DAYS"'),
('"WAREHOUSE_CODE"'),
('"WAREHOUSE_NAME"'),
('"LOCATION"'),
('"QTY_CASES"'),
('"TOTAL_KG"'),
('"TOTAL_VALUE"'),
('"EXPIRY_RISK"'),
('FROM "FreshCo Foods Inc. Inventory"'),
('WHERE "EXPIRY_RISK" LIKE ''%Expired%'';'),
('--View Top 10 SKUs with Expired + Critical Items'),
('SELECT'),
('DISTINCT "SKU"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('WHERE "EXPIRY_RISK" LIKE ''%Expired%'''),
('OR "EXPIRY_RISK" LIKE ''%Critical%'''),
('GROUP BY "SKU"'),
('ORDER BY Total_Plt DESC'),
('LIMIT 10;'),
('--View Top 10 SKUs with Expired Items'),
('SELECT'),
('DISTINCT "SKU"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('SUM("QTY_CASES") AS Total_boxes'),
('SUM("TOTAL_KG") AS Total_Weight'),
('SUM("TOTAL_VALUE") AS Total_Value'),
('FROM "FreshCo Foods Inc. Inventory"'),
('WHERE "EXPIRY_RISK" LIKE ''%Expired%'''),
('GROUP BY "SKU"'),
('ORDER BY Total_Plt DESC'),
('LIMIT 10;'),
('--View Warehouse Utilization Raw Data'),
('SELECT *'),
('FROM "FreshCo Foods Inc. Warehouse Utilization";'),
('--View Available Location by Warehouse'),
('SELECT'),
('"WAREHOUSE_NAME"'),
('"Available Location"'),
('FROM "FreshCo Foods Inc. Warehouse Utilization";'),
('--View Utilization by Warehouse'),
('SELECT'),
('"WAREHOUSE_NAME"'),
('"Warehouse Utilization"'),
('FROM "FreshCo Foods Inc. Warehouse Utilization";'),
('--View Warehouse Nearing Capacity'),
('SELECT *'),
('FROM "FreshCo Foods Inc. Warehouse Utilization"'),
('WHERE "Warehouse Utilization" >= ''0.9'';'),
('--View Dead Stocks by Warehouse'),
('SELECT "WAREHOUSE_NAME"'),
('COUNT("PALLET_ID") AS Total_Plt'),
('FROM "FreshCo Foods Inc. Inventory"'),
('WHERE "EXPIRY_RISK" LIKE ''%Expired%'''),
('GROUP BY "WAREHOUSE_NAME"'),
('ORDER BY Total_Plt DESC;');
